name: area44/autofix.ci
description: Run autofix.ci

runs:
  using: "composite"
  steps:
    - name: Detect Node.js version and package manager
      id: detect_env
      uses: area44/workflows/detect-env@v3.2.0

    - name: Setup PNPM
      if: ${{ steps.detect_env.outputs.package_manager == 'pnpm' }}
      uses: pnpm/action-setup@v4
      with:
        version: ${{ steps.detect_env.outputs.package_manager_version }}

    - name: Setup Bun
      if: ${{ steps.detect_env.outputs.package_manager == 'bun' }}
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ steps.detect_env.outputs.package_manager_version }}

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ steps.detect_env.outputs.node_version }}
        cache-dependency-path: |
          **/package-lock.json
          **/pnpm-lock.yaml
          **/yarn.lock
          **/bun.lock

    - name: Install dependencies
      shell: bash
      run: |
        case "${{ steps.detect_env.outputs.package_manager }}" in
          pnpm)
            pnpm install --prefer-offline --no-frozen-lockfile
            ;;
          yarn)
            yarn install --prefer-offline
            ;;
          bun)
            bun install
            ;;
          *)
            if [[ -f package-lock.json ]]; then
              npm ci
            else
              npm install
            fi
            ;;
        esac

    - name: Run scripts
      shell: bash
      run: |
        scripts="$(node -e "
          const fs = require('fs');
          if (!fs.existsSync('package.json')) process.exit(0);

          const scripts = require('./package.json').scripts || {};

          const cases = [
            ['check'],
            ['format', 'lint'],
            ['fmt', 'lint'],
            ['lint'],
            ['format'],
            ['fmt'],
          ];

          for (const group of cases) {
            if (group.every(name => scripts[name])) {
              console.log(group.join(' '));
              break;
            }
          }
        ")"

        if [[ -n "$scripts" ]]; then
          for script in $scripts; do
            "${{ steps.detect_env.outputs.package_manager }}" run "$script"
          done
        else
          echo "No matching scripts found."
        fi

    - name: Run autofix.ci
      uses: autofix-ci/action@v1
