name: area44/vite
description: Build and Deploy with Vite

runs:
  using: "composite"
  steps:
    - name: Detect Node.js version and package manager
      id: detect_env
      shell: bash
      run: |
        if [[ -f .nvmrc ]]; then
          node_version=$(<.nvmrc)
        else
          node_version="lts/*"
        fi

        package_manager=""
        package_manager_version="latest"

        [[ -f pnpm-lock.yaml ]] && package_manager="pnpm"
        [[ -f yarn.lock ]] && package_manager="${package_manager:-yarn}"
        [[ -f package-lock.json ]] && package_manager="${package_manager:-npm}"
        [[ -f bun.lock ]] && package_manager="${package_manager:-bun}"

        if [[ -z "$package_manager" && -f package.json ]]; then
          raw_package_manager=$(jq -r '.packageManager // empty' package.json)
          if [[ -n "$raw_package_manager" ]]; then
            package_manager="${raw_package_manager%%@*}"
            package_manager_version="${raw_package_manager#*@}"
            [[ "$package_manager" == "$package_manager_version" ]] && package_manager_version="latest"
          else
            package_manager="npm"
          fi
        fi

        echo "node_version=$node_version" >> "$GITHUB_OUTPUT"
        echo "package_manager=$package_manager" >> "$GITHUB_OUTPUT"
        echo "package_manager_version=$package_manager_version" >> "$GITHUB_OUTPUT"
        echo "Detected Node.js: $node_version | Package Manager: $package_manager@$package_manager_version"

    - name: Setup PNPM
      if: ${{ steps.detect_env.outputs.package_manager == 'pnpm' }}
      uses: pnpm/action-setup@v4
      with:
        version: ${{ steps.detect_env.outputs.package_manager_version }}

    - name: Setup Bun
      if: ${{ steps.detect_env.outputs.package_manager == 'bun' }}
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ steps.detect_env.outputs.package_manager_version }}

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ steps.detect_env.outputs.node_version }}
        cache-dependency-path: |
          **/package-lock.json
          **/pnpm-lock.yaml
          **/yarn.lock
          **/bun.lock

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          ~/.npm
          ~/.pnpm-store
          ~/.yarn/cache
          ~/.bun/install/cache
        key: ${{ runner.os }}-${{ steps.detect_env.outputs.package_manager }}-${{ hashFiles('**/package.json', '**/*.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ steps.detect_env.outputs.package_manager }}-

    - name: Install dependencies
      shell: bash
      run: |
        package_manager="${{ steps.detect_env.outputs.package_manager }}"
        "$package_manager" install

    - name: Set environment variables
      shell: bash
      run: |
        repo_name="${{ github.event.repository.name }}"
        echo "base=/$repo_name/" >> "$GITHUB_ENV"

    - name: Build Vite site
      shell: bash
      run: |
        package_manager="${{ steps.detect_env.outputs.package_manager }}"
        "$package_manager" run build

    - name: Upload site artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: dist
