name: area44/astro
description: Build and Deploy Astro Site

runs:
  using: "composite"
  steps:
    - name: Detect Node.js version and package manager
      id: detect_env
      uses: area44/workflows/detect-env@v3.1.1

    - name: Setup PNPM
      if: ${{ steps.detect_env.outputs.package_manager == 'pnpm' }}
      uses: pnpm/action-setup@v4
      with:
        version: ${{ steps.detect_env.outputs.package_manager_version }}

    - name: Setup Bun
      if: ${{ steps.detect_env.outputs.package_manager == 'bun' }}
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ steps.detect_env.outputs.package_manager_version }}

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ steps.detect_env.outputs.node_version }}
        cache-dependency-path: |
          **/package-lock.json
          **/pnpm-lock.yaml
          **/yarn.lock
          **/bun.lock

    - name: Cache dependencies
      uses: actions/cache@v5
      with:
        path: |
          node_modules
          ~/.npm
          ~/.pnpm-store
          ~/.yarn/cache
          ~/.bun/install/cache
          .astro
        key: ${{ runner.os }}-${{ steps.detect_env.outputs.package_manager }}-${{ hashFiles('**/package.json', '**/*.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ steps.detect_env.outputs.package_manager }}-

    - name: Set site variables
      shell: bash
      run: |
        repo_name="${{ github.event.repository.name }}"
        owner="${{ github.repository_owner }}"
        {
          echo "BASE=/$repo_name/" >> "$GITHUB_ENV"
          echo "SITE=https://$owner.github.io"
        } >> "$GITHUB_ENV"

    - name: Install dependencies
      shell: bash
      run: |
        package_manager="${{ steps.detect_env.outputs.package_manager }}"
        $package_manager install

    - name: Build Astro site
      shell: bash
      run: |
        package_manager="${{ steps.detect_env.outputs.package_manager }}"
        $package_manager run build

    - name: Upload site artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: dist
