name: autofix.ci

on:
  workflow_call:  # Make this workflow reusable from other repositories


# Required permission to allow autofix.ci to push changes back to the repository
permissions:
  contents: write

jobs:
  autofix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Setup Biome CLI
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome
        run: biome ci .

      - name: Run autofix.ci
        uses: autofix-ci/action@v1.3
