name: autofix.ci

on:
  workflow_call:

permissions:
  contents: write

jobs:
  autofix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine Node.js version
        id: get_node_version
        run: |
          if [[ -f ".nvmrc" ]]; then
            echo "NODE_VERSION=$(cat .nvmrc | tr -d '\n')" >> "$GITHUB_OUTPUT"
          elif node_version=$(jq -r '.engines.node // empty' package.json); [[ -n "$node_version" ]]; then
            echo "NODE_VERSION=$node_version" >> "$GITHUB_OUTPUT"
          else
            echo "NODE_VERSION=lts/*" >> "$GITHUB_OUTPUT"
          fi

      - name: Detect package manager
        id: detect_pm
        run: |
          default_pm="npm"
          default_pm_version="latest"
          if [[ -f "package.json" ]] && jq -e '.packageManager' package.json > /dev/null; then
            raw_pm=$(jq -r '.packageManager' package.json)
            pm_name="${raw_pm%@*}"
            pm_version="${raw_pm#*@}"
          else
            pm_name="$default_pm"
            pm_version="$default_pm_version"
          fi
          echo "PM_NAME=$pm_name" >> "$GITHUB_OUTPUT"
          echo "PM_VERSION=$pm_version" >> "$GITHUB_OUTPUT"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.get_node_version.outputs.NODE_VERSION }}
          cache: ${{ steps.detect_pm.outputs.PM_NAME }}

      - name: Setup PNPM
        if: ${{ steps.detect_pm.outputs.PM_NAME == 'pnpm' }}
        uses: pnpm/action-setup@v4
        with:
          version: ${{ steps.detect_pm.outputs.PM_VERSION }}

      - name: Setup Yarn
        if: ${{ steps.detect_pm.outputs.PM_NAME == 'yarn' }}
        uses: DerYeger/setup-yarn@v1
        with:
          version: ${{ steps.detect_pm.outputs.PM_VERSION }}

      - name: Setup Bun
        if: ${{ steps.detect_pm.outputs.PM_NAME == 'bun' }}
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ steps.detect_pm.outputs.PM_VERSION }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/.pnpm-store
            ~/.bun
            .yarn/cache
          key: ${{ runner.os }}-${{ steps.detect_pm.outputs.PM_NAME }}-${{ hashFiles('**/package-lock.json', '**/pnpm-lock.yaml', '**/yarn.lock', '**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.detect_pm.outputs.PM_NAME }}-

      - name: Install dependencies
        run: |
          case "${{ steps.detect_pm.outputs.PM_NAME }}" in
            pnpm) pnpm install --no-frozen-lockfile ;;
            yarn) yarn install ;;
            bun)  bun install ;;
            *)    npm install ;;
          esac

      - name: Setup Biome CLI
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome
        run: biome check

      - name: Run autofix.ci
        uses: autofix-ci/action@v1
