name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Unit Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Setup environment
        uses: ./setup
        with:
          node-version: "24.17.0"

      - name: Run Main Tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Verify build artifacts
        run: |
          test -f dist/detect-env.js
