name: autofix.ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Project
        run: |
          rm -rf autofix-project
          mkdir -p autofix-project
          cd autofix-project
          echo '{"name": "autofix-project", "scripts": {"lint": "echo \"linting...\""}}' > package.json
          npm install --no-package-lock

      - name: Test Autofix Action
        uses: ./autofix
