name: test-vite
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test Vite Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dummy Project
        run: |
          rm -rf dummy-vite
          mkdir -p dummy-vite
          cd dummy-vite
          echo '{"name": "dummy-vite", "scripts": {"build": "mkdir -p dist && touch dist/index.html"}}' > package.json
          npm install --no-package-lock

      - name: Test Vite Action
        uses: ./vite
        id: vite_action
        with:
          path: dummy-vite/dist
          build-command: "cd dummy-vite && npm run build"

      - name: Verify Vite Outputs
        run: |
          if [ -z "${{ steps.vite_action.outputs.node-version }}" ]; then exit 1; fi
