name: Test Lint/Format action
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Setup Project
        run: |
          rm -rf lint-format-project
          mkdir -p lint-format-project
          cd lint-format-project
          echo '{"name": "lint-format-project", "scripts": {"lint": "echo \"linting...\""}}' > package.json
          npm install --no-package-lock

      - name: Detect Node.js version and package manager
        shell: bash
        id: detect_env
        run: node "dist/detect-env.js"

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: ${{ steps.detect_env.outputs.node-version }}

      - name: Run lint script (Direct Test)
        run: |
          cd lint-format-project
          node "../dist/run-scripts.js"
