name: test-astro
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dummy Project
        run: |
          rm -rf dummy-astro
          mkdir -p dummy-astro
          cd dummy-astro
          echo '{"name": "dummy-astro", "engines": {"node": "20"}, "scripts": {"build": "mkdir -p dist && touch dist/index.html"}}' > package.json
          npm install --no-package-lock

      - name: Test Astro Action
        uses: ./astro
        id: astro_action
        with:
          path: dummy-astro/dist
          build-command: "cd dummy-astro && npm run build"

      - name: Verify Astro Outputs
        run: |
          if [ -z "${{ steps.astro_action.outputs.node-version }}" ]; then exit 1; fi
