name: Test Lint/Format action
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Setup Project
        run: |
          rm -rf lint-format-project
          mkdir -p lint-format-project
          cd lint-format-project
          echo '{"name": "lint-format-project", "scripts": {"lint": "echo \"linting...\""}}' > package.json
          npm install --no-package-lock

      - name: Detect enviroment
        shell: bash
        id: detect_env
        run: node "dist/detect-env.mjs"

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ steps.detect_env.outputs.node-version }}

      - name: Run lint script (Direct Test)
        run: |
          cd lint-format-project
          node "../dist/run-scripts.mjs"
